project:
  type: website
  render:
  - "01*.qmd"
  - "*.qmd"

website:
  title: "Billboard Hot 100"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - auto: "*.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged
    code-overflow: wrap
    
    